# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

on:
  push:
    tags:
      - '*'

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: dotnet publish -o ./build /p:DebugType=embedded
      - name: Package
        run: tar -czf NorthShirahebi.tar.gz -C build .
      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: NorthShirahebi.tar.gz
  